export const theme = {
  brand: "cyan",
  primary: "cyan",
  muted: "gray",
  faint: "gray",
  accent: "yellow",
  success: "green",
  danger: "red",
  rail: "gray",
  border: "gray",
  code: "white",
  text: "white",
} as const;

export const icons = {
  assistant: "◆",
  user: "›",
  tool: "◇",
  running: "●",
  done: "✓",
  error: "!",
  cursor: "▌",
  image: "▧",
  rail: "│",
  railGap: "┆",
  node: "●",
  runningFrames: ["·", "•", "●", "•"],
  cursorFrames: ["▌", "▍"],
  inputIdle: "○",
  inputActive: "●",
} as const;
